---
- name: detalhes interfaces
  hosts: all
  become: true

  tasks:
    - name: Pega nome interface
      command: find /sys/class/net -type l -not -lname '*virtual*' -printf '%f\n'
      register: physical_interfaces_cmd
      changed_when: false
      check_mode: false

    - name: Exibe detalhes das interfaces
      debug:
        msg: "{{ lookup('vars', 'ansible_' + item) }}"
      loop: "{{ physical_interfaces_cmd.stdout_lines }}"


# fonte: Zeitounator 
# url: https://stackoverflow.com/questions/55880443/how-to-get-a-list-of-physical-network-interfaces-with-ansible
